### ISSUE TITLE
[Installer] Installing on systems with RST/BitLocker

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/desktop-design#155]
This is the non-epic version of [web-squad#2284](https://github.com/canonical-web-and-design/web-squad/issues/2284)

_Request from: Martin Wimpress and Iain Lane_

It is not currently possible to install Ubuntu on RAID (RST) disks or install alongside Windows on Bitlocked disks. So we need warnings in the installer to guide users when encountering these scenarios.

We need two notifications in the installer to warn the user when installing in RST mode.

1. You have RST and need to turn something off in the BIOs and do something in Windows if you want to keep on dual-booting.
1. You have Bitlocked harddrive you need to switch that off in the in Windows.

With a simple wiki link to read more. For example https://wiki.ubuntu.com/rst

**Comment by matthewpaulthomas** [comment]
Answers from meeting:

> At what point could the installer know that your device can’t have Ubuntu installed?

Could be whenever we like.

> Is it possible for a device to fall into both categories, i.e. RST _and_ BitLocker? If so, would we detect both?

If you're in RST mode you can't see any disks at all. Once you've switched out of RST (into AHCI) you might discover that the disk has BitLocker as well.

Example use case for BitLocker is that you buy a Dell that you know Ubuntu will run well on, but right now it’s running Windows.

BIOS might refer to RST as “RAID”.

> Would the instructions be short enough to fit on this screen itself?

Yes, but maybe not useful because you're going to need to reboot to perform them.

https://superuser.com/questions/1280141/switch-raid-to-ahci-without-reinstalling-windows-10

>  Would it be practical to e-mail them? Or print them to a printer?

Probably not, they're probably connected to the Internet but don’t have e-mail set up or printers configured.

Could use QR code as well as showing URL.

> Do you need to reverse the instructions after installing?

When you switch RST to AHCI, then reboot to Windows, it might panic and go into recovery mode. If you switch within Windows, it will take you through a recovery process.

BitLocker: We don’t know.

**Comment by matthewpaulthomas** [comment]
Draft design complete:
- [RST](https://docs.google.com/document/d/1bZ4yQIVgGaUGSYu3qiUHnQt3ieBZoqunP_DcleHCr3I/edit#heading=h.l9zmuy5zf43z)
- [BitLocker](https://docs.google.com/document/d/1bZ4yQIVgGaUGSYu3qiUHnQt3ieBZoqunP_DcleHCr3I/edit#heading=h.an5e8lyg0x2v)

**Comment by lilyvidenova** [comment]
+1 with a few little changes :)
